added kittysay to cli/quality-of-life package set, because there can be no quality of life without kitties; updated flake; added config for custom iso images (needs work, copy-pasted and poorly rewritten code from nixpkgs); nixified awesomewm config and added as dependency; unified installation module loader; added gemini cli in new dev/ai package set; made kitty pickup FONT_SIZE env variable (useful in iso for HiDPI scenarios); changed sddm theme to catppuccin; split system/system package set into base and laptop; added tools/hardware-tools package set with all the hardware debugging/info goodies.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -72,7 +72,10 @@ if type nixos-rebuild &>/dev/null; then
   echo "${info}Flake path: ${dim}path:${thisDir}${clr}"
   echo "${info}Flake attribute: ${dim}${attributeRef}${clr}"
 
-  prompt "Proceed?" inverse
+  prompt "Proceed?" inverse || {
+    echo "${info}Aborting";
+    exit 1;
+  }
 
   echo "path:${thisDir}" | sudo tee /etc/nixos/flake-ref >/dev/null
   echo "${attributeRef}" | sudo tee /etc/nixos/host-ref >/dev/null
